source: .
destination: ./_site
includes: ./_includes
baseurl: null
relative_url: "https://mmeendez8.github.io"
url: "https://mmeendez8.github.io"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed