source: .
destination: ./_site
includes: ./_includes
baseurl: null
relative_url: "https://miguel-mendez-ai.com"
url: "https://miguel-mendez-ai.com"
permalink: /:year/:month/:day/:title

markdown: kramdown
highlighter: none
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed