source: .
destination: ./_site
includes: ./_includes
baseurl: null
relative_url: "https://miguel-mendez-ai"
url: "https://miguel-mendez-ai"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed