source: .
destination: ./_site
includes: ./_includes
baseurl: null
relative_url: "https://miguel-mendez-ai.com"
url: "https://miguel-mendez-ai.com"
permalink: /:year/:month/:day/:title
title: "Miguel Mendez AI Blog"
description: "Miguel Mendez personal website. Posts about Machine Learning and Deep Learning."

markdown: kramdown
highlighter: none
kramdown:
  input: GFM

# Removes content from rss feed https://github.com/jekyll/jekyll-feed?tab=readme-ov-file#excerpt-only-flag
feed:
  excerpt_only: true
  posts_limit: 15


plugins:
  - jekyll-sitemap
  - jekyll-feed